import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { store } from '@/store/store'
import { Provider } from 'react-redux'
import './globals.scss'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}
const inter = Inter({
	weight: ['400', '500', '600', '700'],
	style: 'normal',
	subsets: ['latin'],
	variable: '--var-inter',
})

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={inter.variable}>{children}</body>
		</html>
	)
}
