import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import Layout from '@/components/layout/Layout'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}
const inter = Inter({
	weight: ['400', '500', '600', '700'],
	style: 'normal',
	subsets: ['latin'],
	variable: '--var-inter',
})

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={inter.variable}>
				<Layout>{children}</Layout>
			</body>
		</html>
	)
}
